name: Selenium Test Workflow
on: push

jobs:
  Selenium_Test_Job1:
    name: Selenium Test Job1
    runs-on: ubuntu-latest
    env:
      SELENIUM_DRIVER: 'RemoteWebDriver'

    steps:
      - run: echo "This is running inside a ${{ runner.os }} server in Github"
      - name: Check out Source code
        uses: actions/checkout@v4.2.2
      - run: echo "This repo is ${{ github.repository }}.."
      - name: Run a inline script
        run: |
          mkdir newfolder
          ls -l
        shell: bash
      - name: Execute during failure
        if: ${{ failure() }}
        run: echo "one of the step seems failed"
      - name: Run Selenium Test
        if: ${{ env.SELENIUM_DRIVER == 'RemoteWebDriver' }}
        run: echo "Running test in Selenium grid setup"
        
  Selenium_Test_Job2:
    name: Selenium Test Job2
    runs-on: ubuntu-latest
    needs: Selenium_Test_Job1
    if: ${{ always() }}
    
    steps:
      - run: echo "This is from second job"
